code --install-extension 2gua.rainbow-brackets
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension arrterian.nix-env-selector
code --install-extension bajdzis.vscode-database
code --install-extension batisteo.vscode-django
code --install-extension bbenoist.Nix
code --install-extension buenon.scratchpads
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension cpmcgrath.codealignment-vscode
code --install-extension Dagger.dagger
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension erd0s.terraform-autocomplete
code --install-extension exiasr.hadolint
code --install-extension foxundermoon.shell-format
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension HookyQR.beautify
code --install-extension humao.rest-client
code --install-extension ionutvmi.path-autocomplete
code --install-extension jamesottaway.nix-develop
code --install-extension jnoortheen.nix-ide
code --install-extension johnpapa.vscode-peacock
code --install-extension kevinkyang.auto-comment-blocks
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension mindginative.terraform-snippets
code --install-extension mitchdenny.ecdc
code --install-extension mkhl.direnv
code --install-extension mrmlnc.vscode-json5
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension nrwl.angular-console
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension PascalReitermann93.vscode-yaml-sort
code --install-extension paulvarache.vscode-taskfile
code --install-extension pinage404.nix-extension-pack
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension ryu1kn.partial-diff
code --install-extension secanis.jenkinsfile-support
code --install-extension shanoor.vscode-nginx
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Tchoupinax.tilt
code --install-extension timonwong.shellcheck
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wholroyd.jinja
code --install-extension yzhang.markdown-all-in-one
