#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

# echo "Init submodules"
# yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi


  echo "Setting up dock"
  source ./dock.sh

  echo "Setting OSX defaults"
  source ./macos.sh


  echo "Setting Firefox as default"
  open /Applications/Firefox\ Developer\ Edition.app/ -setDefaultBrowser

  echo "VS Code setup"
  code --install-extension Shan.code-settings-sync
  ln -s $HOME/.vscode/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
  ln -s $HOME/.vscode/keybindings.json $HOME/Library/Application\ Support/Code/User/keybindings.json
  ln -s $HOME/.vscode/snippets/ $HOME/Library/Application\ Support/Code/User

  # default shell

  # default terminal

  # default browser
fi



echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:elocke/dotfiles.git"
