#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

# echo "Init submodules"
# yadm submodule update --recursive --init

system_type=$(uname -s)
BREW_PREFIX=$(brew --prefix)

if [ "$system_type" = "Darwin" ]; then
  # SDK headers
  sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew update
    brew bundle --global
    brew cleanup
  fi

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi

	sudo dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
  if ! fgrep -q "/bin/zsh" /etc/shells; then
    echo "/bin/zsh" | sudo tee -a /etc/shells;
    chsh -s "/bin/zsh";
  fi;

  echo "Setting up dock"
  source ./scripts/dock

  echo "Setting OSX defaults"
  source ./scripts/macos

  echo "VS Code setup"
  ln -s $HOME/.vscode/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
  ln -s $HOME/.vscode/keybindings.json $HOME/Library/Application\ Support/Code/User/keybindings.json
  ln -s $HOME/.vscode/snippets/ $HOME/Library/Application\ Support/Code/User

  echo "Python setup"
  source ./scripts/python

  echo "Setting Firefox as default"
  open /Applications/Firefox.app/ -setDefaultBrowser

fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:elocke/dotfiles.git"
